### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by andypiper** [henrytriplette/python-brachiograph-gui#3]
Hi! It would be great to know what license this is released under, there's nothing specified in the README and no LICENSE file in the repo. Thanks!

**Comment by henrytriplette** [comment]
Hi! Thanks for the question, but I must admit I knew very little about licenses when I started this project, and now everything I do for work is handled by different legal teams, so I never took time to investigate further. 

But I d'love to update the repo with an appropriate license. 

Does something like "do wathever you like, as long as the code stays open and available to anybody" exist? Not sure if it's MIT or maybe GPL?

**Comment by andypiper** [comment]
Totally works for me (in either case, MIT or GPL). Bonus, I'm giving a talk tomorrow about contributing to OSS, and planned to use this - based on the fact that I've been using the code locally and now want to be able to send PRs or post a modified version - and realised that it was an example of wanting to clarify the license, so thanks for being my example use case! 👍🏻 

To satisfy the "open and available to anybody" I think you'd probably (?) prefer GPL (per [Choose A License](https://choosealicense.com/licenses/gpl-3.0/)), but it's your original project so take a look at their license navigator and see what you think. Upstream Brachiograph which this (sort of) incorporates is MIT, though.

**Comment by henrytriplette** [comment]
Nice! Hope your talk went well. 
Will it be available on streaming/YouTube/other broadcast? 

At the I took a look at different licenses and went for GPL, I liked the part about "making available complete source code of licensed works and modifications". Thanks for the suggestion!

**Comment by andypiper** [comment]
Talk was good - it is being broadcast as a full online event in a few weeks actually (online rather than in-person) https://www.eventbrite.co.uk/e/609416189227
